# Generated by Django 4.2.25 on 2026-04-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_description_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
